services:
  - type: web
    name: hologrip
    runtime: python
    plan: free

    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app

    healthCheckPath: /health

    envVars:
      - key: PYTHON_VERSION
        value: 3.12.10

      - key: SECRET_KEY
        generateValue: true

      - key: SELF_PING_INTERVAL
        value: "10"